name: focusnow
description: "A new Flutter project."
publish_to: "none"
version: 0.0.2+2
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  subscription_repository:
    path: packages/subscription_repository
  analytics_repository:
    path: packages/analytics_repository
  review_repository:
    path: packages/review_repository
  form_inputs:
    path: packages/form_inputs
  study_session_repository:
    path: packages/study_session_repository
  challenge_repository:
    path: packages/challenge_repository
  stats_repository:
    path: packages/stats_repository
  goal_repository:
    path: packages/goal_repository
  notification_repository:
    path: packages/notification_repository
  user_repository:
    path: packages/user_repository


  supabase_flutter: ^2.5.7
  google_sign_in: ^6.1.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  font_awesome_flutter: ^10.1.0
  formz: ^0.7.0
  flow_builder: ^0.0.9
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  skeletonizer: ^1.4.1+1
  hydrated_bloc: ^9.1.5
  flutter_emoji: ^2.5.1
  in_app_purchase: ^3.2.0
  purchases_flutter: ^8.5.1
  purchases_ui_flutter: ^8.5.1
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  cached_network_image: ^3.4.1
  flutter_keyboard_visibility: ^6.0.0
  lottie: ^3.3.1
  flutter_glow: ^0.3.0
  fl_chart: ^0.71.0
  intl: ^0.20.2
  confetti: ^0.8.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - .env
