create table "public"."image_generation_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "timestamp" timestamp with time zone default now(),
    "status" text default 'failed'::text
);


alter table "public"."image_generation_logs" enable row level security;

CREATE UNIQUE INDEX image_generation_logs_pkey ON public.image_generation_logs USING btree (id);

alter table "public"."image_generation_logs" add constraint "image_generation_logs_pkey" PRIMARY KEY using index "image_generation_logs_pkey";

alter table "public"."image_generation_logs" add constraint "image_generation_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."image_generation_logs" validate constraint "image_generation_logs_user_id_fkey";

grant delete on table "public"."image_generation_logs" to "anon";

grant insert on table "public"."image_generation_logs" to "anon";

grant references on table "public"."image_generation_logs" to "anon";

grant select on table "public"."image_generation_logs" to "anon";

grant trigger on table "public"."image_generation_logs" to "anon";

grant truncate on table "public"."image_generation_logs" to "anon";

grant update on table "public"."image_generation_logs" to "anon";

grant delete on table "public"."image_generation_logs" to "authenticated";

grant insert on table "public"."image_generation_logs" to "authenticated";

grant references on table "public"."image_generation_logs" to "authenticated";

grant select on table "public"."image_generation_logs" to "authenticated";

grant trigger on table "public"."image_generation_logs" to "authenticated";

grant truncate on table "public"."image_generation_logs" to "authenticated";

grant update on table "public"."image_generation_logs" to "authenticated";

grant delete on table "public"."image_generation_logs" to "service_role";

grant insert on table "public"."image_generation_logs" to "service_role";

grant references on table "public"."image_generation_logs" to "service_role";

grant select on table "public"."image_generation_logs" to "service_role";

grant trigger on table "public"."image_generation_logs" to "service_role";

grant truncate on table "public"."image_generation_logs" to "service_role";

grant update on table "public"."image_generation_logs" to "service_role";


