name: Flutter CI/CD to Google Play Console

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      # Step: Create .env file from secret
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

  build:
    needs: test
    name: Build
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "oracle"
          java-version: "17"

        #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #5 Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' > android/key.properties
          echo 'keyPassword=${{ secrets.KEY_PASSWORD }}' >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: List Keystore Contents
        run: |
          keytool -list -v -keystore android/app/keystore.jks -storepass '${{ secrets.KEYSTORE_PASSWORD }}'

      - name: Creating .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

        #7 Building App Bundle (aab)
      - name: Build appBundle
        run: flutter build appbundle --release

      - name: Build APK
        run: flutter build apk --release

        #9 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the artifact created in the 'test' job
      - name: Download appbundle artifact
        uses: actions/download-artifact@v4
        with:
          name: appbundle

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: apk

      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.vollrath.focusnow
          releaseFiles: app-release.aab
          track: production
          status: draft
          changesNotSentForReview: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"
          body: "This release includes the latest app bundle and APK."
          artifacts: |
            app-release.aab
            app-release.apk
