name: Flutter Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      # Step: Copy .env-template to .env
      - name: Copy .env-template to .env
        run: cp .env-template .env
        working-directory: ./mobile

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./mobile

      - name: Run tests
        run: flutter test
        working-directory: ./mobile
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: supabase start
      - run: supabase functions serve & sleep 3
      - run: deno test --allow-all ./functions/tests
        working-directory: ./supabase/
