name: Flutter Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      # Step: Copy .env-template to .env
      - name: Copy .env-template to .env
        run: cp .env-template .env
        working-directory: ./mobile

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./mobile

      - name: Run tests
        run: flutter test
        working-directory: ./mobile
